services:
  front-chat:
    build: .
    ports:
      -  "3000:3000"
    volumes:
      - /tmp
    networks:
      - default
      - live-chat
  
networks:
  default:
    driver: bridge
  live-chat:
    external: true
